<a href="https://colab.research.google.com/github/rajan5639/Assignemnt_numpy/blob/main/Copy_of_NUMPy_Assignmen_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1.**Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

In [ ]:
'''
Numpy is a python Library which is used to evaluate/compute   the mathematical data either creating the
Numpy array, Matrix , addition, subtraction, divison, no.of element in the list, their shape etc.

It's a specalised Library , whose main goal/ aim to evaluate the mathematica data efficently/fastly/accurately.
As we know c++ is the fastest programming  Language , and priority of c come after c++ , our numpy Library
including the their module and package made by the c language. so its computaion speed much better than other
data structure in python , who is able to store the data and capable to do mathematical operations Like list.

Numpy store the data in the form of array ,as we know array store the homo genous data. to acces the data from
the memory its quite easier beacuse data of numpy array store in contigious memory location.

It is very usefull for scientific computing and data analysis:--
[1] caluclating the mean of data to anylsie/ figure out the detail of data
[2] caluclating the trignometry angle  to anylsie/ figure out dependence/ correlation bw the data going to  append in the model
[3] sort the data
[4] access any data / creating the random array to check the perform,ance of model


etc.
'''

# 2. **Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

In [ ]:
'''
both np.mean() and np.average() calculate the average(arthematic mean) of number

but np.average() can calculte the  the averahe of weights

but no.mean() can only calculate the mean of numerical number


uses ->
np.mean() -----> to evaluate the mean of number
np.average() -----> to evaluate the mean of number with weights


'''

 **Q3.Describe the methods for reversing a NumPy array
along different axes. Provide examples for 1D and 2D
 arrays** .

In [ ]:
'''
to reverse the array we use the Numpy array , you can use the np.flip() method


1D array :->
'''
arr = np.array([1,2,3,4,45])
print(np.flip(arr))

# 2D array :-->
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('\n\n')
reversed_rows = np.flip(arr,axis = 0)  # reversing the row wise
print(reversed_rows)
print('\n\n')
reversed_columns = np.flip(arr,axis = 1)  # reversing the column wise
print(reversed_columns)



[45  4  3  2  1]
[[1 2 3]
 [4 5 6]]



[[4 5 6]
 [1 2 3]]



[[3 2 1]
 [6 5 4]]


4.**How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance**

In [ ]:
'''
we calculate the datatype of np array
type(np.array([---Data----]))

It's a specalised Library , whose main goal/ aim to evaluate the mathematica data efficently/fastly/accurately.
As we know c++ is the fastest programming  Language , and priority of c come after c++ , our numpy Library
including the their module and package made by the c language. so its computaion speed much better than other
data structure in python , who is able to store the data and capable to do mathematical operations Like list.

Numpy store the data in the form of array ,as we know array store the homo genous data. to acces the data from
the memory its quite easier beacuse data of numpy array store in contigious memory location.

'''

# Q5**.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

In [ ]:
'''
ndarrays referse to the  number of dimension of array , which is basically arise when the programmer wanna to calculate the data type of Numpy
Like type(np.array([---Data----]))

 A = np.array([[1,2,3,4], [23,5,6,9]])
 print(A)
 print(type(A))

so to evaluate the number of dimension :
np.array([1,2,3,4,5]).shape -> tells how many rows and columns

Both python List and numpy used to store the data , but the differenec is List store the hetrogenous data and data is store in heap memory
which is quite complex to the procesor to access the data from the memory due to hetrogenous in nature , data has not presen particular location

* it requiore the more time and quite complex for the processor to deal their data

while numpy array store the dta in the form of array ,as we know array store the homo genous data. to acces the data from
the memory its quite easier beacuse data of numpy array store in contigious memory location.

* * it requiore the less time and not  complex for the processor to deal numpy data data


'''

# 6. **Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

In [ ]:
'''
As Numpy array is designed to deal with the major/minor operation of mathematical in programming language ,so Numpy array has a lot of benefit over List:
1) easier to evaluta the  central tendency of data
    * Mean , Mode , Median

2) can easily  convert in to matric s0, we can anylise the ddata well

3) having the Large scale data  and to evaluate/ compute operation --> numpy as much better and fastest way to compute

4) havig a lot of function/formula/ method inside the Numpy array which make the progammer to be skilled for every operation

5) we can reshape the data , according to aur requirement. for bettr understanding
'''


Q7.**Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output**

In [ ]:
'''
Both vstack() and hstack() are NumPy functions used to stack arrays, but they differ in the way they stack them.

vstack(): ---> stacks arrays vertically (row-wise), increasing the number of rows in the resultant array.
            :--> store the (row -wise)data in vertically order
'''
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a,b)))

'''
hstack()   :-> stacks arrays horizontally (column-wise), increasing the number of columns in the resultant array.
           :->  store the (column -wise)data in horizontally order
'''
print('\n\n')
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
print(np.hstack((a,b)))



[[1 2 3]
 [4 5 6]]



[[1 4]
 [2 5]
 [3 6]]


# Q8.**Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**

In [ ]:
'''
Both np.fliplr() and np.flipud() are NumPy functions used to reverse the elements of an array, but they differ in the direction of reversal.
np.fliplr() flips the entries in each row in the left/right direction. Columns are preserved, but appear in a different order than before.
'''
arr_2d = np.array([[1,2,3],[4,5,6]])
print(np.fliplr(arr_2d))

'''
np.flipud() flips the entries in each column in the up/down direction. Rows are preserved, but appear in a different order than before.
'''
print('\n\n')
arr_2d = np.array([[1,2,3],[4,5,6]])  # column has flip up/down direction
print(np.flipud(arr_2d))


[[3 2 1]
 [6 5 4]]



[[4 5 6]
 [1 2 3]]


# **Q9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven split?**

In [ ]:
'''
The array_split() method in NumPy is used to split an array into multiple sub-arrays.

'''

a = np.arange(8)
print(a)
print(np.array_split(a, 3))

'''
we are splitting the array in to 3 sub-parts

In the above example, we split an array of 8 elements into 3 sub-arrays.
If the array cannot be split evenly, the function distributes the elements as evenly as possible among the sub-arrays.
The first several sub-arrays will have one more element than the remaining ones.
'''
print('\n\n')
a = np.arange(16).reshape(4,4)
print(a)

print(np.array_split(a, 2, axis=1))


[0 1 2 3 4 5 6 7]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


**10. Explain the concepts ofvectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

In [ ]:
'''
Vectorization is the process of applying operations to entire arrays instead of individual elements.
NumPy achieves this by leveraging optimized, low-level implementations written in C, which significantly speeds up computations.

For example, to add two arrays a and b element-wise, instead of using a loop, you can simply write
'''



#NumPy handles the element-wise addition internally, without explicit looping in Python.
'''
Broadcasting extends vectorization by allowing arithmetic operations between arrays of different shapes, under certain conditions. NumPy automatically "stretches" the smaller array to match the shape of the larger array, enabling efficient element-wise operations without manual resizing or looping.

For example, adding a scalar to an array:


a = np.array([1, 2, 3])
b = 2
c = a + b  # Broadcasts b to match the shape of a
'''

'''
Both vectorization and broadcasting eliminate the need for explicit Python loops, which are often performance bottlenecks.
By leveraging optimized C implementations and automatic shape adjustments, NumPy enables concise and highly efficient array operations.
 This is crucial for numerical computations in data science, machine learning, and scientific computing, where large arrays are commonly processed.
'''


In [ ]:
a = np.array([1, 2, 3])
b = 2
c = a + b  # Broadcasts b to match the shape of a
print(c)

Z = np.zeros((3,4))
Z=Z+5
print(Z)        # eg of broadcasting adding the element having different shape by element wise
                # instead of loop wise
                # matrix multiplication element wise

[3 4 5]


array([5., 5., 5., 5., 5.])

1. **Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [ ]:
import numpy as np


In [ ]:
arr = np.random.randint(1,101,(3,3))
print(arr)

[[ 6 97 48]
 [41 68 71]
 [ 3 52 97]]


In [ ]:
arr.T

array([[ 6, 41,  3],
       [97, 68, 52],
       [48, 71, 97]])

2. **Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [ ]:
Arr = np.random.random_sample(10)
Arr

array([0.6557655 , 0.51727114, 0.92260672, 0.28796992, 0.08769942,
       0.18701023, 0.21812429, 0.22701224, 0.67419024, 0.66578736])

In [ ]:
Arr.reshape(2,5)

array([[0.09216363, 0.02002012, 0.43334184, 0.8371637 , 0.22815037],
       [0.93162819, 0.49564685, 0.51444658, 0.6766604 , 0.12375474]])

In [ ]:
Arr.reshape(5*2)

array([0.09216363, 0.02002012, 0.43334184, 0.8371637 , 0.22815037,
       0.93162819, 0.49564685, 0.51444658, 0.6766604 , 0.12375474])

3. *** Create a 4x4 NumPy array with random float values. Add a border of zeros
 around it, resulting in a 6x6 array.***

In [ ]:
Arr = np.random.rand(4,4)
Arr

array([[0.91573336, 0.93531035, 0.00248969, 0.80743489],
       [0.40730332, 0.77248381, 0.32788189, 0.62961259],
       [0.79708205, 0.46762198, 0.57415967, 0.75621393],
       [0.01942742, 0.14780546, 0.56467403, 0.3437501 ]])

In [ ]:
temp = np.zeros((6,6))
temp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
temp[1:-1,1:-1] = Arr

temp

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.91573336, 0.93531035, 0.00248969, 0.80743489,
        0.        ],
       [0.        , 0.40730332, 0.77248381, 0.32788189, 0.62961259,
        0.        ],
       [0.        , 0.79708205, 0.46762198, 0.57415967, 0.75621393,
        0.        ],
       [0.        , 0.01942742, 0.14780546, 0.56467403, 0.3437501 ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

4. **Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [ ]:
Arr = np.arange(10,60,5)
Arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
Arr = np.array(['python','numpy','pandas'])
np.char.upper(Arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
np.char.lower(Arr)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.title(Arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

**6.Generate a NumPy array of words. Insert a space between each character of every word in the array.**





['h e l l o' 'w o r l d' 'n u m p y']


7.**Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [ ]:
Arr1 = np.random.randint(10,100,(4,4), dtype = int)
print(Arr1)


[[58 12 36 88]
 [69 46 73 55]
 [93 25 27 63]
 [41 88 23 71]]


In [ ]:
Arr2 = np.random.randint(10,100,(4,4), dtype = int)
print(Arr2)

[[17 97 74 84]
 [94 24 19 52]
 [57 63 28 63]
 [60 30 26 54]]


In [ ]:
Arr1 + Arr2

array([[ 75, 109, 110, 172],
       [163,  70,  92, 107],
       [150,  88,  55, 126],
       [101, 118,  49, 125]])

In [ ]:
Arr1-Arr2

array([[ 41, -85, -38,   4],
       [-25,  22,  54,   3],
       [ 36, -38,  -1,   0],
       [-19,  58,  -3,  17]])

In [ ]:
np.multiply(Arr1,Arr2)

array([[ 986, 1164, 2664, 7392],
       [6486, 1104, 1387, 2860],
       [5301, 1575,  756, 3969],
       [2460, 2640,  598, 3834]])

In [ ]:
np.divide(Arr1,Arr2)

array([[3.41176471, 0.12371134, 0.48648649, 1.04761905],
       [0.73404255, 1.91666667, 3.84210526, 1.05769231],
       [1.63157895, 0.3968254 , 0.96428571, 1.        ],
       [0.68333333, 2.93333333, 0.88461538, 1.31481481]])

**Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [ ]:
A = np.eye(5,5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
diagonal = np.diag(A)
diagonal

array([1., 1., 1., 1., 1.])

# Q9.**Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array**

In [ ]:


def is_prime(no):
  if no==1:
    return False
  for i in range (2,no):
    if no%i==0:
      return False
    else:
      return True



arr = np.random.randint(0,1000,100)
prime_number = []
for i in arr:
  if is_prime(i):
    prime_number.append(i)

print(arr)
print('\n\n\n')

Np = np.array(prime_number)
np.sort(Np)
print(Np)


[418 729 506 130 855 559 863 195 620 879 166 113 601 943 929 599 125 965
 201 416  65  49  77 549 513 718 363 613 472 718  10 458  87 630 907 229
  40 216 705 690 251 259 317 889 331 791 954 955 655  24 349 949 535 578
 463 704  41 326 674 162 394 356 142 841 117  89 253 934  75 642 520 366
 835 537 277  95 619  83 735 952  58 411 226 615 162 473 335 817 919 223
 574 571 532 685 926  94 449 842 810 290]




[729 855 559 863 195 879 113 601 943 929 599 125 965 201  65  49  77 549
 513 363 613  87 907 229 705 251 259 317 889 331 791 955 655 349 949 535
 463  41 841 117  89 253  75 835 537 277  95 619  83 735 411 615 473 335
 817 919 223 571 685 449]


Q10.**Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**

In [ ]:
A = np.random.randint(15, 48,28)
print(A)

A.size

[37 17 25 34 29 15 29 37 36 22 42 19 31 19 29 20 31 37 32 41 30 23 34 28
 38 33 37 38]


28

In [ ]:
mat = np.matrix(A)
mat
print(mat.shape)

mat = mat.reshape(4,7)

print(mat.shape)

(1, 28)
(4, 7)


In [ ]:
print(np.mean(mat[0]))
print(np.mean(mat[1]))
print(np.mean(mat[2]))
print(np.mean(mat[3]))




26.571428571428573
29.428571428571427
31.428571428571427
33.0


In [ ]:
for i in range(4):
  print(i)

0
1
2
3
